spring.application.name=elms-backend

# Server Configuration
server.port=8080
server.forward-headers-strategy=framework

# Import local credentials configuration if present (git-ignored)
spring.config.import=optional:classpath:application-local.properties, optional:file:./application-local.properties

# Spring Data JPA defaults
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update

# Application Environment Custom Property
elms.app.environment=development